version: '3.7'

services:
  slai_postgres:
    container_name: 'slai_postgres'
    restart: "on-failure"
    build: ./ad-hocs/postgres
    env_file:
      - ./src/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./ad-hocs/postgres:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_REMOTE_PORT}
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready' ]
      interval: 10s
      timeout: 2s
      retries: 3
