version: '3.7'

services:
  slai_postgres:
    container_name: 'slai_postgres'
    restart: "on-failure"
    build: ./ad-hocs/postgres
    env_file:
      - ./src/.env
    environment:
      POSTGRES_DB: 'seamless_learning'
      POSTGRES_HOST: localhost'
      POSTGRES_USER: 'seamless_learning'
      POSTGRES_PASSWORD: 'seamless-learning'
    volumes:
      - ./ad-hocs/postgres:/docker-entrypoint-initdb.d
    ports:
      - 5442:5432
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready' ]
      interval: 10s
      timeout: 2s
      retries: 3
    
  slai_mongo:  
    container_name: 'slai_mongo'
    restart: "on-failure"
    image: mongo:latest  
    env_file:
      - ./src/.env  
    environment:
      - MONGO_INITDB_DATABASE=seamless_learning
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./ad-hocs/mongo:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017  # Expose MongoDB port
    healthcheck:
      test: [ 'CMD', 'mongo', '--eval', 'db.runCommand({ connectionStatus: 1 })' ]
      interval: 10s
      timeout: 2s
      retries: 3

  slai_node:  
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
      - "8080:8080"

