CREATE SCHEMA IF NOT EXISTS dvs;

-- DDL generated by Postico 1.5.22
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE dvs.cloud_lab_v2 (
    retired_at timestamp without time zone,
    version uuid NOT NULL,
    removed_at timestamp without time zone,
    first_published_at timestamp without time zone,
    environment jsonb NOT NULL,
    level text NOT NULL,
    image_url text NOT NULL,
    url text NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    author_ids uuid[] NOT NULL,
    duration integer NOT NULL,
    current_status text NOT NULL,
    id uuid PRIMARY KEY,
    last_published_at timestamp without time zone,
    description text NOT NULL,
    title text NOT NULL,
    opportunity_id uuid,
    created_at timestamp without time zone NOT NULL,
    prerequisites text NOT NULL,
    content_url text NOT NULL,
    learning_objective_ids uuid[] NOT NULL,
    slug text,
    sub_status text NOT NULL,
    challenges jsonb[] NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX cloud_lab_v2_pkey ON dvs.cloud_lab_v2(id uuid_ops);